Add label variant to Typography
prenda-school/design-system pull request #358
Opened 2022-02-18 16:05 UTC by shadoath

This is probably an oversimplified PR as it stands now. Look to see what needs to be done next.

[Based on Label in this Figma](https://www.figma.com/file/w9lodWeivyS4GHdBNIYaJr/foundations?node-id=2268%3A228)

2022-02-18 16:12 UTC, WilliamKelley commented
It's that simple! However, The variant is missing its specified font-features-settings of cv05, ss03. You'll have to add another argument to `buildVariant` for that.

2022-02-18 21:47 UTC, WilliamKelley requested changes
I'm not sure what the syntax rules are for `font-feature-settings`. It seems pretty lax, but let's go with the format from inspecting Inter's [official site](https://rsms.me/inter/#features/ss03): 
![image](https://user-images.githubusercontent.com/25781782/154765566-c7f37b7e-306e-4bbf-a5ad-5745dc2a5f2d.png)

2022-02-18 21:47 UTC, WilliamKelley commented on libs/spark/src/theme/__next__typography.ts
> +    "'cv05' on 'ss03 on"
```suggestion
    "'cv05' 1, 'ss03' 1"
```

2022-02-18 21:47 UTC, WilliamKelley commented on libs/spark/src/theme/__next__typography.ts
> +    "'cv05' on 'ss03 on"
```suggestion
    "'cv05' 1, 'ss03' 1"
```

2022-02-18 21:47 UTC, WilliamKelley commented on libs/spark/src/theme/__next__typography.ts
> +    "'cv05' on 'ss03 on"
```suggestion
    "'cv05' 1, 'ss03' 1"
```

2022-02-18 22:33 UTC, WilliamKelley commented
Also, the font file for Inter bold (600 weight) needs to be brought in, and the font face declaration added (to `__next__fontFaces`). You can see on the Storybook that the letters look way to thin compared to the Figma reference, because it's picking the closest available weight file (400).

Also, the `cv05` feature setting does not seem to be working. I can see `ss03` though. Not sure how to debug that. Maybe something went wrong when I put the files through the web-optimizer on fontsquirrel.com .

2022-02-18 22:44 UTC, WilliamKelley commented
More on the [fontsquirrel](https://www.fontsquirrel.com/tools/webfont-generator) generation. I think this is the source of the problem. I've stored the original fonts zips in the repo at `/assets/fonts/zips/Inter...`. Try unzipping that, reuploading to FontSquirrel's Webfont Generator (do like two-at-a-time, it can be finnicky and have a total size limit, so you might have to stop at like 6 files). Choose the "Expert" settings and leave everything as-is, except add what's in the screenshot below:

![image](https://user-images.githubusercontent.com/25781782/154771012-0675a8dd-ed59-44d5-80d8-fd6a3c102698.png)

2022-02-23 15:07 UTC, shadoath commented
I tried to use FontSquirrel this morning but couldn't get it to take any uploaded files. Is there another way or something you can do for this step?

Also where do I put the Release notes?

2022-02-23 15:14 UTC, WilliamKelley commented
Did you try uploading one at a time? If so, I try it myself.

And, `libs/spark/CHANGELOG.md`.

2022-02-24 15:38 UTC, shadoath commented
@WilliamKelley Next step is to use the other subset tools you mentioned in the issue?

2022-02-24 15:58 UTC, WilliamKelley commented
You definitely can. But I won't hold this PR back if you don't want to. It will be pretty involved and can be considered a separate issue for now. Just revert the initial font file replacement and we'll leave that outstanding.

2022-02-24 17:20 UTC, WilliamKelley requested changes
Actually this is fine since there's only the bold(italic) fonts added!

2022-02-24 17:20 UTC, WilliamKelley commented on libs/spark/CHANGELOG.md
> +      - Added.
```suggestion
  - Added `font-feature-settings` for "body" and "description" variants.
  - Added "label" variant (with `font-feature-settings`).
```

2022-02-25 16:47 UTC, WilliamKelley approved these changes

2022-02-25 17:16 UTC, slingner approved these changes

2022-02-25 17:17 UTC, merged

2022-02-25 19:16 UTC, WilliamKelley commented
Reverted because PR title (and resulting squash merge commit) was not in conventional commit style