Adding release notes for Unstable Button
prenda-school/design-system pull request #391
Opened 2022-04-11 19:16 UTC by shadoath

2022-04-11 19:21 UTC, WilliamKelley requested changes

2022-04-11 19:21 UTC, WilliamKelley commented on libs/spark/CHANGELOG.md
> +      - New options: `primary`, `stroked`, `ghost`, and `destructive`.
```suggestion
      - Removed values: `contained`, `outlined`, `text`.
      - Added values: `primary`, `stroked`, `ghost`, `destructive`.
```
consistent terminology (add / remove); reordering values to emphasize the old-to-new map

2022-04-11 19:21 UTC, WilliamKelley commented on libs/spark/CHANGELOG.md
> +    - `focusRipple={*}` -> _removed_
```suggestion
    - `disableElevation` -> _removed_
    - `disableFocusRipple` -> _removed_
    - `disableRipple` -> _removed_
    - `disableTouchRipple` -> _removed_
    - `centerRipple` -> _removed_
    - `focusRipple` -> _removed_
```
These are `boolean` props, so the common usage will be just its presence

2022-04-11 19:21 UTC, WilliamKelley commented on libs/spark/CHANGELOG.md
> +      - `"outlined"` -> `"stroked"`
```suggestion
    - `variant="contained"` -> `variant="primary"`
    - `variant="outlined"` -> `variant="stroked"`
    - `variant="text"` -> `variant="ghost"`
```
each line should be as direct as possible; ordering kept the same as in the previous section

2022-04-11 19:25 UTC, WilliamKelley commented
Can you move the section higher up to be in alphabetical order? So right above `Unstable_CssBaseline` and below the lowercase unstable utilities

2022-04-12 18:01 UTC, shadoath commented
> Can you move the section higher up to be in alphabetical order? So right above Unstable_CssBaseline and below the lowercase unstable utilities

Done!

2022-04-12 20:49 UTC, slingner approved these changes

2022-04-12 21:07 UTC, merged