Updates for Unstable button
prenda-school/design-system pull request #398
Opened 2022-04-27 15:41 UTC by shadoath

- Specifically targeting when the theme Provider of spark v1 has styling overrides.

2022-04-27 15:58 UTC, WilliamKelley requested changes
Title changed to comply to conventional commits.

2022-04-27 15:58 UTC, WilliamKelley commented on libs/spark/CHANGELOG.md
> +
```suggestion
### Fixes

- **Unstable_Button**
  - Override conflicting styles from previous `theme` (e.g. when rendered under `SparkThemeProvider`) for pseudo states like hover, disabled, etc.
```

2022-04-27 15:58 UTC, WilliamKelley commented on libs/spark/src/Unstable_Button/Unstable_Button.tsx
> +      },
```suggestion
      // override V1 theme style
      '&&:disabled': {
        opacity: 'unset',
      },
```
It's only to override the style. Not an existing style that needs double specificity.

2022-04-27 15:58 UTC, WilliamKelley commented on libs/spark/src/Unstable_Button/Unstable_Button.tsx
> +        '&&': {
```suggestion
        // double specificity to override v1 theme style
        '&&': {
```

2022-04-27 15:58 UTC, WilliamKelley commented on libs/spark/src/Unstable_Button/Unstable_Button.tsx
> +        },
```suggestion
```
Pretty sure this was unnecessary.

2022-04-27 16:02 UTC, shadoath commented on libs/spark/src/Unstable_Button/Unstable_Button.tsx
> +        },
Correct...whoops

2022-04-27 16:14 UTC, shadoath commented
@WilliamKelley, I had forgot about that. It is just so nice to hit merge commit. 
I could turn the PR to draft and do it though then bring it back out to trigger only one chromatic merge right?

2022-04-27 16:16 UTC, shadoath commented
Or use the 'batch' ill use that more.

2022-04-28 00:51 UTC, WilliamKelley commented
Oh, it looks like even successful runs have that error message, but it doesnt exit the process with an error code and fail the job, it exits fine.

So we should follow with the workaround described in the issue

2022-04-28 13:25 UTC, shadoath commented
So we need to do the following: 
```
variables:
  GIT_CHECKOUT: 'false'

before_script:
  - git checkout "$CI_COMMIT_REF_NAME"
  ```

2022-04-28 17:30 UTC, WilliamKelley commented
> So we need to do the following?
> 
> ```
> variables:
>   GIT_CHECKOUT: 'false'
> 
> before_script:
>   - git checkout "$CI_COMMIT_REF_NAME"
> ```

I believe those are GitLab specific, so it would be the equivalent GitHub Actions env var? I'm not sure. 

Regardless though, it seems like it succeeded once you added an empty line between a list item and a heading! Which makes sense because the absence of that would cause format:check to fail. So it just has a poor output.

2022-04-28 17:32 UTC, WilliamKelley approved these changes

2022-04-29 17:39 UTC, WilliamKelley commented
@slingner review bump. we can get this released today

2022-04-29 18:03 UTC, slingner approved these changes
🚀

2022-04-29 18:07 UTC, merged